version: "3"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d
    ports:
      - "1433:1433"
    restart: always
